//
// Created by rgerst on 25.02.19.
//

#pragma once
#include <misaxx/core/misa_task.h>

namespace misaxx_indexer {

    /**
     * The serialization schemata generated by the framework might be incomplete (e.g. they do not include children)
     * This task traverses the serialization schemata and builds a new file that contains all data types
     */
    struct schema_traversion_task : public misaxx::misa_task {

        using misaxx::misa_task::misa_task;

        void work() override;

        void create_parameters(misaxx::misa_parameter_builder &t_parameters) override;
    };
}

